name: Api CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: just echo a message
      run: |
        echo Hello there!
      
  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment: development
    steps:
    - name: just echo a message for deploy to dev
      run: |
        echo Hello there!
          
  deploy_to_beta:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    if: github.event_name != 'pull_request'
    environment: prod
    steps:
    - name: Download a Deployment Zip
      uses: actions/download-artifact@v2
      with:
        name: deployment_zip
    - name: Download a Deployment Script
      uses: actions/download-artifact@v2
      with:
        name: deployment_script
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure Deploy Resources
      if: github.event_name != 'pull_request'
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: |
          chmod +x ./deploy-backend.sh
          ./deploy-backend.sh -z deploy.zip -r 2wr-beta-resources -e 2wrbeta   
