name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  JAVA_VERSION: '11'                  # set this to the Java version to use

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: just echo a message
      run: |
        echo Hello there!
  deployment:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job echo test
        run: |
          echo Hello from the run test
